/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModuloInterfazUsuario;

import ModuloEstructuras.ListaEnlazada;
import ModuloEstructuras.NodoLista;
import static ModuloInterfazUsuario.Dashboard.ShowJPanel;
import ModuloInterfazUsuario.table.TableHeaderAlignment;
import ModuloInterfazUsuario.table.checkBoxTableHeaderRenderer;
import ModuloModelos.Estacion;
import ModuloModelos.Horario;
import ModuloModelos.Ruta;
import ModuloModelos.Tren;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nath_
 */
public class resumenRutasPanel extends javax.swing.JPanel {
   
    ListaEnlazada<Ruta> rutas;
    
    public void agregarRuta(String id,Tren tren, Horario horario, ListaEnlazada<Estacion> estacionesVisitadas){
    rutas.agregarAlFinal(new Ruta(id,tren,horario, estacionesVisitadas));
}
public void eliminarTren(String id){
        NodoLista<Ruta> actual = rutas.getCabeza();
        while(actual!=null){
            if(actual.getDato().getId().equals(id)){
                rutas.eliminar(actual.getDato());
                break;
            }
            actual = actual.getSiguiente();
        }
      
    }
public void editarTrenes(String id, Horario horario, Tren tren, ListaEnlazada<Estacion> estaciones){
        NodoLista<Ruta> actual= rutas.getCabeza();
        while(actual!=null){
            if(actual.getDato().getId().equals(id)){
                actual.getDato().setTren(tren); ;
                actual.getDato().setHorario(horario);
                actual.getDato().setEstaciones(estaciones);
                break;
            
            }
            actual = actual.getSiguiente();
        }
        
    }
   
   

 

    
    public resumenRutasPanel() {
       
        initComponents();
        setPreferredSize(new Dimension(1510,820));
        init();
        
    }
    public void init(){
        txtBusqueda.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ingrese el nombre de la ruta");
        txtBusqueda.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("Imagenes/search.svg"));
        table.getColumnModel().getColumn(0).setHeaderRenderer(new checkBoxTableHeaderRenderer(table, 0));
        table.getTableHeader().setDefaultRenderer(new TableHeaderAlignment(table));
       
        testData();
       
    }
     private void testData(){
        DefaultTableModel model = (DefaultTableModel)table.getModel();

         model.addRow(new Object[] {false, 1, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 2, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 3, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 4, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 5, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 6, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 7, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 8,"Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 9, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 10, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 11, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 12, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 13, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        model.addRow(new Object[] {false, 14, "Nathalia Sofia", "Tren 1", "Estacion A, Estacion B, Estacion C", "10:30", "12:40"});
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBusqueda = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBusqueda.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 172, 1226, 59));

        btnBorrar.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Roboto ExtraBold", 1, 24)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 698, 139, 59));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELECT", "ID", "NOMBRE", "TREN", "ESTACIONES", "HORA SALIDA", "HORA LLEGADA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 250, 1400, -1));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Roboto ExtraBold", 1, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 172, 139, 59));

        btnNuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevo.setFont(new java.awt.Font("Roboto ExtraBold", 1, 24)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 698, 139, 59));

        btnEditar.setBackground(new java.awt.Color(0, 0, 0));
        btnEditar.setFont(new java.awt.Font("Roboto ExtraBold", 1, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1158, 698, 139, 59));

        lblTitulo.setFont(new java.awt.Font("Roboto ExtraBold", 1, 48)); // NOI18N
        lblTitulo.setText("Rutas");
        add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 78, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
      
        ShowJPanel(new agregarrutaPanel());
    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        ShowJPanel(new agregarrutaPanel());
    }//GEN-LAST:event_btnEditarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
