/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ModuloInterfazUsuario;

import static ModuloInterfazUsuario.Dashboard.ShowJPanel;
import ModuloInterfazUsuario.table.TableHeaderAlignment;
import ModuloInterfazUsuario.table.checkBoxTableHeaderRenderer;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nath_
 */
public class resumenTrenesPanel extends javax.swing.JPanel {

    /**
     * Creates new form resumenTrenesPanel
     */
    public resumenTrenesPanel() {
        initComponents();
        
        setPreferredSize(new Dimension(1510,820));
        init();
    }
     public void init(){
        fieldBuscar.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ingrese el id del tren");
        fieldBuscar.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, new FlatSVGIcon("Imagenes/search.svg"));
        
        table.getColumnModel().getColumn(0).setHeaderRenderer(new checkBoxTableHeaderRenderer(table, 0));
        table.getTableHeader().setDefaultRenderer(new TableHeaderAlignment(table));
       
        testData();
       
    }
     private void testData(){
        DefaultTableModel model = (DefaultTableModel)table.getModel();

        model.addRow(new Object[] {false, 1, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 2, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 3, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 4, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 5, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 6, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 7, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 8, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 9, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 10, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 11, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 12, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 13, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        model.addRow(new Object[] {false, 14, "Nathalia Sofia", 100, "Vagón A, Vagón B, Vagón C"});
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        fieldBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        scrollTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto ExtraBold", 1, 48)); // NOI18N
        jLabel10.setText("Trenes");
        jLabel10.setRequestFocusEnabled(false);
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 78, -1, -1));

        fieldBuscar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBuscarActionPerformed(evt);
            }
        });
        add(fieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 172, 1226, 59));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Roboto ExtraBold", 1, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 172, 139, 59));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SELECT", "ID", "NOMBRE", "KILOMETRAJE", "VAGONES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollTable.setViewportView(table);

        add(scrollTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 250, 1393, -1));

        btnBorrar.setBackground(new java.awt.Color(0, 0, 0));
        btnBorrar.setFont(new java.awt.Font("Roboto ExtraBold", 1, 24)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1309, 698, 139, 59));

        btnEditar.setBackground(new java.awt.Color(0, 0, 0));
        btnEditar.setFont(new java.awt.Font("Roboto ExtraBold", 1, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1158, 698, 139, 59));

        btnNuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevo.setFont(new java.awt.Font("Roboto ExtraBold", 1, 24)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1007, 698, 139, 59));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBuscarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
    ShowJPanel(new agregarTrenPanel());    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        ShowJPanel(new agregarTrenPanel());
    }//GEN-LAST:event_btnEditarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JTextField fieldBuscar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
